// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.DataContext.Context;

#nullable disable

namespace MovieApp.DataContext.Migrations
{
    [DbContext(typeof(MovieAppDbContext))]
    [Migration("20251125175937_MoviesDataFinal")]
    partial class MoviesDataFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieApp.DataContext.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 13,
                            Name = "War"
                        },
                        new
                        {
                            Id = 14,
                            Name = "History"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Western"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Family"
                        });
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 0.0,
                            Description = "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
                            Director = "Frank Darabont",
                            PosterUrl = "https://image.tmdb.org/t/p/original/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 0.0,
                            Description = "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
                            Director = "Francis Ford Coppola",
                            PosterUrl = "https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
                            ReleaseYear = 1972,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 0.0,
                            Description = "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
                            Director = "Christopher Nolan",
                            PosterUrl = "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 0.0,
                            Description = "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
                            Director = "Quentin Tarantino",
                            PosterUrl = "https://image.tmdb.org/t/p/original/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
                            ReleaseYear = 1994,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 0.0,
                            Description = "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
                            Director = "Steven Spielberg",
                            PosterUrl = "https://image.tmdb.org/t/p/original/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
                            ReleaseYear = 1993,
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 0.0,
                            Description = "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men...",
                            Director = "Peter Jackson",
                            PosterUrl = "https://image.tmdb.org/t/p/original/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
                            ReleaseYear = 2003,
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            Id = 7,
                            AverageRating = 0.0,
                            Description = "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination.",
                            Director = "Peter Jackson",
                            PosterUrl = "https://image.tmdb.org/t/p/original/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
                            ReleaseYear = 2001,
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 8,
                            AverageRating = 0.0,
                            Description = "Frodo Baggins and the other members of the Fellowship continue on their sacred quest to destroy the One Ring--but on separate paths...",
                            Director = "Peter Jackson",
                            PosterUrl = "https://image.tmdb.org/t/p/original/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
                            ReleaseYear = 2002,
                            Title = "The Lord of the Rings: The Two Towers"
                        },
                        new
                        {
                            Id = 9,
                            AverageRating = 0.0,
                            Description = "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy...",
                            Director = "David Fincher",
                            PosterUrl = "https://image.tmdb.org/t/p/original/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
                            ReleaseYear = 1999,
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 10,
                            AverageRating = 0.0,
                            Description = "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
                            Director = "Robert Zemeckis",
                            PosterUrl = "https://image.tmdb.org/t/p/original/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
                            ReleaseYear = 1994,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 11,
                            AverageRating = 0.0,
                            Description = "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: inception, the implantation of another person's idea into a target's subconscious.",
                            Director = "Christopher Nolan",
                            PosterUrl = "https://image.tmdb.org/t/p/original/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 12,
                            AverageRating = 0.0,
                            Description = "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
                            Director = "Lana Wachowski",
                            PosterUrl = "https://image.tmdb.org/t/p/original/p96dm7sCMn4VYAStA6siNz30G1r.jpg",
                            ReleaseYear = 1999,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 13,
                            AverageRating = 0.0,
                            Description = "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
                            Director = "Martin Scorsese",
                            PosterUrl = "https://image.tmdb.org/t/p/original/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
                            ReleaseYear = 1990,
                            Title = "GoodFellas"
                        },
                        new
                        {
                            Id = 14,
                            AverageRating = 0.0,
                            Description = "The epic saga continues as Luke Skywalker learns the ways of the Jedi from master Yoda while the rebellion faces the might of the Galactic Empire.",
                            Director = "Irvin Kershner",
                            PosterUrl = "https://image.tmdb.org/t/p/original/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
                            ReleaseYear = 1980,
                            Title = "The Empire Strikes Back"
                        },
                        new
                        {
                            Id = 15,
                            AverageRating = 0.0,
                            Description = "Clarice Starling is a top student at the FBI academy. Jack Crawford wants her to interview Dr. Hannibal Lecter, a brilliant psychiatrist and cannibalistic serial killer, hoping he has insight into a related case.",
                            Director = "Jonathan Demme",
                            PosterUrl = "https://image.tmdb.org/t/p/original/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
                            ReleaseYear = 1991,
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = 16,
                            AverageRating = 0.0,
                            Description = "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the seven deadly sins, unraveling a dark and disturbing string of murders.",
                            Director = "David Fincher",
                            PosterUrl = "https://image.tmdb.org/t/p/original/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
                            ReleaseYear = 1995,
                            Title = "Se7en"
                        },
                        new
                        {
                            Id = 17,
                            AverageRating = 0.0,
                            Description = "A group of explorers travel through a wormhole near Saturn in search of a new home for humanity as Earth becomes uninhabitable.",
                            Director = "Christopher Nolan",
                            PosterUrl = "https://image.tmdb.org/t/p/original/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 18,
                            AverageRating = 0.0,
                            Description = "During WWII, a group of U.S. soldiers are sent behind enemy lines to retrieve a paratrooper whose brothers were killed in combat.",
                            Director = "Steven Spielberg",
                            PosterUrl = "https://image.tmdb.org/t/p/original/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
                            ReleaseYear = 1998,
                            Title = "Saving Private Ryan"
                        },
                        new
                        {
                            Id = 19,
                            AverageRating = 0.0,
                            Description = "A death row prison guard meets a mysterious inmate with a miraculous gift that changes the lives of those around him.",
                            Director = "Frank Darabont",
                            PosterUrl = "https://image.tmdb.org/t/p/original/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg",
                            ReleaseYear = 1999,
                            Title = "The Green Mile"
                        },
                        new
                        {
                            Id = 20,
                            AverageRating = 0.0,
                            Description = "A betrayed Roman general seeks revenge against the corrupt emperor who murdered his family and sent him into slavery.",
                            Director = "Ridley Scott",
                            PosterUrl = "https://image.tmdb.org/t/p/original/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
                            ReleaseYear = 2000,
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 21,
                            AverageRating = 0.0,
                            Description = "Young lion prince Simba, eager to one day become king, must confront his past and find his rightful place in the Circle of Life.",
                            Director = "Roger Allers",
                            PosterUrl = "https://image.tmdb.org/t/p/original/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
                            ReleaseYear = 1994,
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id = 22,
                            AverageRating = 0.0,
                            Description = "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in Boston.",
                            Director = "Martin Scorsese",
                            PosterUrl = "https://image.tmdb.org/t/p/original/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
                            ReleaseYear = 2006,
                            Title = "The Departed"
                        },
                        new
                        {
                            Id = 23,
                            AverageRating = 0.0,
                            Description = "A talented young drummer enrolls at a music conservatory where he is mentored by an instructor known for his terrifying teaching methods.",
                            Director = "Damien Chazelle",
                            PosterUrl = "https://image.tmdb.org/t/p/original/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
                            ReleaseYear = 2014,
                            Title = "Whiplash"
                        },
                        new
                        {
                            Id = 24,
                            AverageRating = 0.0,
                            Description = "Two magicians' rivalry escalates into a dangerous battle filled with obsession, deception, and tragic consequences.",
                            Director = "Christopher Nolan",
                            PosterUrl = "https://image.tmdb.org/t/p/original/bdN3gXuIZYaJP7ftKK2sU0nPtEA.jpg",
                            ReleaseYear = 2006,
                            Title = "The Prestige"
                        },
                        new
                        {
                            Id = 25,
                            AverageRating = 0.0,
                            Description = "A small-time con man spins a dark and twisted story about the legendary criminal mastermind Keyser Söze.",
                            Director = "Bryan Singer",
                            PosterUrl = "https://image.tmdb.org/t/p/original/99X2SgyFunJFXGAYnDv3sb9pnUD.jpg",
                            ReleaseYear = 1995,
                            Title = "The Usual Suspects"
                        },
                        new
                        {
                            Id = 26,
                            AverageRating = 0.0,
                            Description = "The story of Polish Jewish musician Władysław Szpilman and his struggle to survive the destruction of the Warsaw ghetto.",
                            Director = "Roman Polanski",
                            PosterUrl = "https://image.tmdb.org/t/p/original/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
                            ReleaseYear = 2002,
                            Title = "The Pianist"
                        },
                        new
                        {
                            Id = 27,
                            AverageRating = 0.0,
                            Description = "A reprogrammed Terminator is sent back in time to protect John Connor from a more advanced and deadly machine.",
                            Director = "James Cameron",
                            PosterUrl = "https://image.tmdb.org/t/p/original/jFTVD4XoWQTcg7wdyJKa8PEds5q.jpg",
                            ReleaseYear = 1991,
                            Title = "Terminator 2: Judgment Day"
                        },
                        new
                        {
                            Id = 28,
                            AverageRating = 0.0,
                            Description = "Teenager Marty McFly is accidentally sent back to 1955, disrupting his parents' first meeting and risking his own existence.",
                            Director = "Robert Zemeckis",
                            PosterUrl = "https://image.tmdb.org/t/p/original/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg",
                            ReleaseYear = 1985,
                            Title = "Back to the Future"
                        },
                        new
                        {
                            Id = 29,
                            AverageRating = 0.0,
                            Description = "Batman returns after eight years in exile to face the masked terrorist Bane and save Gotham from destruction.",
                            Director = "Christopher Nolan",
                            PosterUrl = "https://image.tmdb.org/t/p/original/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
                            ReleaseYear = 2012,
                            Title = "The Dark Knight Rises"
                        },
                        new
                        {
                            Id = 30,
                            AverageRating = 0.0,
                            Description = "After his identity is revealed, Peter Parker seeks help from Doctor Strange, leading to multiverse-shattering consequences.",
                            Director = "Jon Watts",
                            PosterUrl = "https://image.tmdb.org/t/p/original/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
                            ReleaseYear = 2021,
                            Title = "Spider-Man: No Way Home"
                        },
                        new
                        {
                            Id = 31,
                            AverageRating = 0.0,
                            Description = "After the devastating events of Infinity War, the remaining Avengers assemble once more to undo Thanos' actions and restore balance to the universe.",
                            Director = "Anthony Russo",
                            PosterUrl = "https://image.tmdb.org/t/p/original/bR8ISy1O9XQxqiy0fQFw2BX72RQ.jpg",
                            ReleaseYear = 2019,
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 32,
                            AverageRating = 0.0,
                            Description = "The Avengers and their allies must be willing to sacrifice everything as they face the powerful Thanos who aims to collect all six Infinity Stones.",
                            Director = "Joe Russo",
                            PosterUrl = "https://image.tmdb.org/t/p/original/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
                            ReleaseYear = 2018,
                            Title = "Avengers: Infinity War"
                        },
                        new
                        {
                            Id = 33,
                            AverageRating = 0.0,
                            Description = "A freed slave teams up with a German bounty hunter to rescue his wife from a brutal Mississippi plantation owner.",
                            Director = "Quentin Tarantino",
                            PosterUrl = "https://image.tmdb.org/t/p/original/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
                            ReleaseYear = 2012,
                            Title = "Django Unchained"
                        },
                        new
                        {
                            Id = 34,
                            AverageRating = 0.0,
                            Description = "A New York stockbroker rises to immense wealth through corruption and fraud, but his life spirals out of control as the FBI closes in.",
                            Director = "Martin Scorsese",
                            PosterUrl = "https://image.tmdb.org/t/p/original/kW9LmvYHAaS9iA0tHmZVq8hQYoq.jpg",
                            ReleaseYear = 2013,
                            Title = "The Wolf of Wall Street"
                        },
                        new
                        {
                            Id = 35,
                            AverageRating = 0.0,
                            Description = "A U.S. Marshal investigates the disappearance of a patient from a mental institution, uncovering shocking and unsettling truths.",
                            Director = "Martin Scorsese",
                            PosterUrl = "https://image.tmdb.org/t/p/original/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg",
                            ReleaseYear = 2010,
                            Title = "Shutter Island"
                        },
                        new
                        {
                            Id = 36,
                            AverageRating = 0.0,
                            Description = "An insurance salesman begins to suspect that his entire life is actually part of a meticulously crafted reality TV show.",
                            Director = "Peter Weir",
                            PosterUrl = "https://image.tmdb.org/t/p/original/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
                            ReleaseYear = 1998,
                            Title = "The Truman Show"
                        },
                        new
                        {
                            Id = 37,
                            AverageRating = 0.0,
                            Description = "Mark Zuckerberg creates a social networking site at Harvard that grows into Facebook, but personal and legal complications follow.",
                            Director = "David Fincher",
                            PosterUrl = "https://image.tmdb.org/t/p/original/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
                            ReleaseYear = 2010,
                            Title = "The Social Network"
                        },
                        new
                        {
                            Id = 38,
                            AverageRating = 0.0,
                            Description = "Bounty hunters seek refuge from a blizzard, but tensions rise as betrayal and deception unfold inside a remote cabin.",
                            Director = "Quentin Tarantino",
                            PosterUrl = "https://image.tmdb.org/t/p/original/jIywvdPjia2t3eKYbjVTcwBQlG8.jpg",
                            ReleaseYear = 2015,
                            Title = "The Hateful Eight"
                        },
                        new
                        {
                            Id = 39,
                            AverageRating = 0.0,
                            Description = "A hunter stumbles across drug money, sparking a violent pursuit from a relentless and chilling hitman.",
                            Director = "Joel Coen",
                            PosterUrl = "https://image.tmdb.org/t/p/original/6d5XOczc226jECq0LIX0siKtgHR.jpg",
                            ReleaseYear = 2007,
                            Title = "No Country for Old Men"
                        },
                        new
                        {
                            Id = 40,
                            AverageRating = 0.0,
                            Description = "A desperate family schemes to infiltrate the household of a wealthy family, leading to shocking consequences.",
                            Director = "Charles Band",
                            PosterUrl = "https://image.tmdb.org/t/p/original/4DGPORlVIDIQvsuSDnM4uXKMjWS.jpg",
                            ReleaseYear = 1982,
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 41,
                            AverageRating = 0.0,
                            Description = "A mentally troubled comedian is driven to madness, sparking a violent revolution and becoming the infamous criminal mastermind known as the Joker.",
                            Director = "Todd Phillips",
                            PosterUrl = "https://image.tmdb.org/t/p/original/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
                            ReleaseYear = 2019,
                            Title = "Joker"
                        },
                        new
                        {
                            Id = 42,
                            AverageRating = 0.0,
                            Description = "In a post-apocalyptic wasteland, Max teams up with Furiosa to escape a tyrant and survive the brutal desert.",
                            Director = "George Miller",
                            PosterUrl = "https://image.tmdb.org/t/p/original/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
                            ReleaseYear = 2015,
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            Id = 43,
                            AverageRating = 0.0,
                            Description = "A retired hitman seeks vengeance against the criminals who stole everything from him, unleashing pure, stylish mayhem.",
                            Director = "Chad Stahelski",
                            PosterUrl = "https://image.tmdb.org/t/p/original/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
                            ReleaseYear = 2014,
                            Title = "John Wick"
                        },
                        new
                        {
                            Id = 44,
                            AverageRating = 0.0,
                            Description = "A paraplegic Marine is sent to the moon Pandora on a unique mission and becomes torn between following orders and protecting its alien inhabitants.",
                            Director = "James Cameron",
                            PosterUrl = "https://image.tmdb.org/t/p/original/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg",
                            ReleaseYear = 2009,
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 45,
                            AverageRating = 0.0,
                            Description = "A frontiersman maimed by a bear fights for survival and hunts down those who betrayed him.",
                            Director = "Alejandro González Iñárritu",
                            PosterUrl = "https://image.tmdb.org/t/p/original/ji3ecJphATlVgWNY0B0RVXZizdf.jpg",
                            ReleaseYear = 2015,
                            Title = "The Revenant"
                        },
                        new
                        {
                            Id = 46,
                            AverageRating = 0.0,
                            Description = "Stranded on Mars, astronaut Mark Watney must rely on his ingenuity to survive and signal to Earth that he is alive.",
                            Director = "Ridley Scott",
                            PosterUrl = "https://image.tmdb.org/t/p/original/3ndAx3weG6KDkJIRMCi5vXX6Dyb.jpg",
                            ReleaseYear = 2015,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 47,
                            AverageRating = 0.0,
                            Description = "A jazz musician and an aspiring actress fall in love while struggling to chase their dreams in Los Angeles.",
                            Director = "Damien Chazelle",
                            PosterUrl = "https://image.tmdb.org/t/p/original/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
                            ReleaseYear = 2016,
                            Title = "La La Land"
                        },
                        new
                        {
                            Id = 48,
                            AverageRating = 0.0,
                            Description = "A theme park featuring living dinosaurs descends into chaos when the prehistoric creatures escape.",
                            Director = "Steven Spielberg",
                            PosterUrl = "https://image.tmdb.org/t/p/original/bRKmwU9eXZI5dKT11Zx1KsayiLW.jpg",
                            ReleaseYear = 1993,
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id = 49,
                            AverageRating = 0.0,
                            Description = "Five high school students in Saturday detention discover they have much more in common than they ever imagined.",
                            Director = "John Hughes",
                            PosterUrl = "https://image.tmdb.org/t/p/original/wM9ErA8UVdcce5P4oefQinN8VVV.jpg",
                            ReleaseYear = 1985,
                            Title = "The Breakfast Club"
                        },
                        new
                        {
                            Id = 50,
                            AverageRating = 0.0,
                            Description = "Armies gather for the final battle of Middle-earth while Frodo and Sam journey toward Mount Doom to destroy the One Ring.",
                            Director = "Peter Jackson",
                            PosterUrl = "https://image.tmdb.org/t/p/original/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
                            ReleaseYear = 2003,
                            Title = "The Lord of the Rings: The Return of the King"
                        });
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.ViewHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("ViewHistory");
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.Favorite", b =>
                {
                    b.HasOne("MovieApp.DataContext.Entities.Movie", "Movie")
                        .WithMany("Favorites")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.DataContext.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.MovieGenre", b =>
                {
                    b.HasOne("MovieApp.DataContext.Entities.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.DataContext.Entities.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.Rating", b =>
                {
                    b.HasOne("MovieApp.DataContext.Entities.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.DataContext.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.ViewHistory", b =>
                {
                    b.HasOne("MovieApp.DataContext.Entities.Movie", "Movie")
                        .WithMany("ViewHistory")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.DataContext.Entities.User", "User")
                        .WithMany("ViewHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.Movie", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("MovieGenres");

                    b.Navigation("Ratings");

                    b.Navigation("ViewHistory");
                });

            modelBuilder.Entity("MovieApp.DataContext.Entities.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Ratings");

                    b.Navigation("ViewHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
